name          'puppet-logclient'
version       '0.1.0'
source        'https://github.com/pgomersbach/puppet-logclient.git'
author        'Paul Gomersbach'
license       'Apache 2.0'
summary       'Logstash client puppet module'
description   ''
project_page  'https://github.com/pgomersbach/puppet-logclient'

dependency 'puppetlabs/stdlib'
